name: intensivevr_pub
description: Mobile app for IntensiveVR PUB

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gradient_text: ^1.0.2
  flutter_bloc: ^6.1.1
  bloc: ^6.1.1
  equatable: ^1.2.5
  dartz: ^0.9.2
  formz: ^0.3.2
  jwt_decoder: ^1.0.3
  backdrop: ^0.4.7
  barcode_widget: ^1.5.0
  carousel_slider: ^2.3.1
  pull_to_refresh: ^1.6.4
  shared_preferences: ^0.5.12+4
  day_night_switcher: ^0.1.1+1
  data_connection_checker: ^0.3.4
  palette_generator: ^0.2.3
  auth_buttons: ^0.0.4
  easy_localization: ^2.3.3+1
  authentication_repository:
    path: packages/authentication_repository
dev_dependencies:
  lint: ^1.5.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
